version: "3"
services:
  front-end:
    build: ./front-end
    ports:
      - "3000:3001"
  back-end:
    build: ./back-end
    ports:
      - "4000:4001"
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
    links:
      - front-end
      - back-end
