name: Docker Compose Actions
on:
  push:
    branches:
      - docker-compose
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Build the stack
        run: docker-compose up -d
